// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaabHPWTIqX7DiHePKov_UccY8DmW80-g',
    appId: '1:449364953077:web:e02d027582cedc1c5002bc',
    messagingSenderId: '449364953077',
    projectId: 'flexomatic-e3ed7',
    authDomain: 'flexomatic-e3ed7.firebaseapp.com',
    storageBucket: 'flexomatic-e3ed7.appspot.com',
    measurementId: 'G-DVV5S5VCG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFR8DP_A8aQiwWVkuZ91pPSuH7Q6gYjA',
    appId: '1:449364953077:android:0e8fe48d4582368d5002bc',
    messagingSenderId: '449364953077',
    projectId: 'flexomatic-e3ed7',
    storageBucket: 'flexomatic-e3ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPBsDqkjlM-i40ZJSuIo3a7aC-vWAsro',
    appId: '1:449364953077:ios:6625d71f9bc9aa9e5002bc',
    messagingSenderId: '449364953077',
    projectId: 'flexomatic-e3ed7',
    storageBucket: 'flexomatic-e3ed7.appspot.com',
    iosClientId: '449364953077-1lm43q9hhm38mlfu3bs7so6p0enfa8h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexomatic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPBsDqkjlM-i40ZJSuIo3a7aC-vWAsro',
    appId: '1:449364953077:ios:6625d71f9bc9aa9e5002bc',
    messagingSenderId: '449364953077',
    projectId: 'flexomatic-e3ed7',
    storageBucket: 'flexomatic-e3ed7.appspot.com',
    iosClientId: '449364953077-1lm43q9hhm38mlfu3bs7so6p0enfa8h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexomatic',
  );
}
